services:
  - type: web
    name: civicaid-voice
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_SANDBOX_FROM
        value: "whatsapp:+14155238886"
      - key: GEMINI_API_KEY
        sync: false
      - key: DEMO_MODE
        value: "true"
      - key: LLM_LIVE
        value: "true"
      - key: WHISPER_ON
        value: "true"
      - key: LLM_TIMEOUT
        value: "6"
      - key: WHISPER_TIMEOUT
        value: "12"
      - key: FLASK_ENV
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"
      - key: AUDIO_BASE_URL
        value: "https://civicaid-voice.onrender.com/static/cache"
      - key: OBSERVABILITY_ON
        value: "true"
      - key: STRUCTURED_OUTPUT_ON
        value: "false"
      - key: GUARDRAILS_ON
        value: "true"
      - key: RAG_ENABLED
        value: "false"
    healthCheckPath: /health
